export default [
{
"login": "AmirhoseinHesami",
"id": 86534843,
"node_id": "MDQ6VXNlcjg2NTM0ODQz",
"avatar_url": "https://avatars.githubusercontent.com/u/86534843?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/AmirhoseinHesami",
"html_url": "https://github.com/AmirhoseinHesami",
"followers_url": "https://api.github.com/users/AmirhoseinHesami/followers",
"following_url": "https://api.github.com/users/AmirhoseinHesami/following{/other_user}",
"gists_url": "https://api.github.com/users/AmirhoseinHesami/gists{/gist_id}",
"starred_url": "https://api.github.com/users/AmirhoseinHesami/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/AmirhoseinHesami/subscriptions",
"organizations_url": "https://api.github.com/users/AmirhoseinHesami/orgs",
"repos_url": "https://api.github.com/users/AmirhoseinHesami/repos",
"events_url": "https://api.github.com/users/AmirhoseinHesami/events{/privacy}",
"received_events_url": "https://api.github.com/users/AmirhoseinHesami/received_events",
"type": "User",
"site_admin": false
},
{
"login": "oxica",
"id": 88445174,
"node_id": "MDQ6VXNlcjg4NDQ1MTc0",
"avatar_url": "https://avatars.githubusercontent.com/u/88445174?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/oxica",
"html_url": "https://github.com/oxica",
"followers_url": "https://api.github.com/users/oxica/followers",
"following_url": "https://api.github.com/users/oxica/following{/other_user}",
"gists_url": "https://api.github.com/users/oxica/gists{/gist_id}",
"starred_url": "https://api.github.com/users/oxica/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/oxica/subscriptions",
"organizations_url": "https://api.github.com/users/oxica/orgs",
"repos_url": "https://api.github.com/users/oxica/repos",
"events_url": "https://api.github.com/users/oxica/events{/privacy}",
"received_events_url": "https://api.github.com/users/oxica/received_events",
"type": "User",
"site_admin": false
}
]