export default {
"login": "piotgie",
"id": 67604867,
"node_id": "MDQ6VXNlcjY3NjA0ODY3",
"avatar_url": "https://avatars.githubusercontent.com/u/67604867?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/piotgie",
"html_url": "https://github.com/piotgie",
"followers_url": "https://api.github.com/users/piotgie/followers",
"following_url": "https://api.github.com/users/piotgie/following{/other_user}",
"gists_url": "https://api.github.com/users/piotgie/gists{/gist_id}",
"starred_url": "https://api.github.com/users/piotgie/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/piotgie/subscriptions",
"organizations_url": "https://api.github.com/users/piotgie/orgs",
"repos_url": "https://api.github.com/users/piotgie/repos",
"events_url": "https://api.github.com/users/piotgie/events{/privacy}",
"received_events_url": "https://api.github.com/users/piotgie/received_events",
"type": "User",
"site_admin": false,
"name": "Piotr Gaik",
"company": null,
"blog": "",
"location": "Gliwice, Poland",
"email": null,
"hireable": true,
"bio": "another self-taught guy",
"twitter_username": null,
"public_repos": 75,
"public_gists": 0,
"followers": 2,
"following": 2,
"created_at": "2020-06-29T19:03:02Z",
"updated_at": "2021-12-30T21:33:30Z"
};
